M48
; DRILL file {KiCad 7.0.2} date Wed May  1 19:32:12 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-01T19:32:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.7445Y-1.4194
X4.9355Y-1.4194
T2
X4.7327Y-1.3001
X4.9473Y-1.3001
T0
M30
